#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  git clone "https://github.com/rockymadden/slack-cli" "$shome/vendor/slacki-cli-${SLACK_CLI_VERSION}" || true
  pushd "$shome/vendor/slacki-cli-${SLACK_CLI_VERSION}" > /dev/null
  git reset --hard "v${SLACK_CLI_VERSION}"
  popd > /dev/null
  mkdir -p "$shome/bin"
  ln -nfs "../vendor/slacki-cli-${SLACK_CLI_VERSION}/src/slack" "$shome/bin/"
}

main "$@"
