#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_slack="0.0.1"
  jq -n --arg slack "$ver_slack" '{slack: $slack}'
}

version "$@"
